server:
  error:
    include-stacktrace: always

spring:
  application:
    name: demospring
  datasource:
    url: jdbc:mysql://localhost:3306/student?createDatabaseIfNoExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: false
#    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
  endpoint:
    health:
      show-details: when_authorized

info:
  app: Spring Boot 2 Essentials
  website: https://github.com/robinsonvs
  github: https://github.com/robinsonvs/spring-boot-essentials

