server:
  error:
    include-stacktrace: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
